# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Tailwind
    - name: Build
      run: dotnet build Tailwind --no-restore
    - name: Test
      run: dotnet test Tailwind --no-build --verbosity normal
      
    - name: Publish to NuGet
      if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet nuget push --skip-duplicate --api-key ${{secrets.TAILWIND_NUGET_KEY}} --source 'https://api.nuget.org/v3/index.json' ${{github.workspace}}/Tailwind/**/Tailwind.*.nupkg
